#!/bin/bash

echo "STARTING TEST"

{ echo "NSBOPENUSB"; echo "NSBSYNCPULSE"; sleep 1; echo "NSBSYNCPULSE"; sleep 1; echo "NSBSYNCPULSE"; echo "NSBCLOSEUSB"; cat; } | nc 127.0.0.1 8903

echo "ENDING TEST"
