#!/bin/bash

echo "STARTING TEST"

{ echo "FNSBOPENUSB"; echo "FNSBSYNCPULSE"; sleep 1; echo "FNSBSYNCPULSE"; sleep 1; echo "FNSBSYNCPULSE"; echo "FNSBCLOSEUSB"; cat; } | nc 127.0.0.1 8903

echo "ENDING TEST"
